name: First workflow
on: push
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
      - name: Run script
        run: |
          echo Hello World
          ls
          cat readme.md
      - name: Run asci output
        run: cowsay -f dragon "Run for cover i am a DRAGON" >> dragon.txt
