name: Generate ascii workflow
on: push
jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
      - name: run script
        run: |
          chmod +x asci-script.sh
          ./asci-script.sh
      - name: List files
        run: ls
