name: Generate ascii workflow
on: push
jobs:
  build-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
      - name: run script
        run: |
          chmod +x asci-script.sh
          ./asci-script.sh
      - name: List files
        run: ls

  test-job:
    needs: build-job
    runs-on: ubuntu-latest
    steps:
      - name: sleep for 10 seconds
        run: sleep 10
      - name: run script
        run: grep -i "dragon" dragon.txt
  deploy-job:
    needs: build-job
    runs-on: ubuntu-latest
    steps:
      - name: Test if dragon is visible
        run: cat dragon.txt
