name: Generate ascii workflow
on: push
jobs:
  build-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
      - name: run script
        run: |
          chmod +x asci-script.sh
          ./asci-script.sh
      - name: Upload the dragon.txt file
        uses: actions/upload-artifact@v7
        with:
          name: dragon-artifact
          path: dragon.txt
  test-job:
    needs: build-job
    runs-on: ubuntu-latest
    steps:
      - name: download the dragon.txt file
        uses: actions/download-artifact@v7
        with:
          name: dragon-artifact
      - name: run script
        run: grep -i "dragon" dragon.txt
  deploy-job:
    needs: build-job
    runs-on: ubuntu-latest
    steps:
      - name: download the dragon.txt file
        uses: actions/download-artifact@v7
        with:
          name: dragon-artifact
      - name: Test if dragon is visible
        run: cat dragon.txt
