name: Matrix workflow
on:
  workflow_dispatch:
  push:

jobs:
  ubuntu-job:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
      - name: Display dummy message
        run: echo "Installing on ${{ matrix.os }}"
